### ISSUE TITLE
Error when using get_osm_data()

### ISSUE THREAD

**Issue by ChimesOfMidnight** [elipousson/overedge#2]
I get an error when trying to make an OSM query. Apparently the variable 'osm_building_tags' can't be found:

```
buildings <- get_osm_data(location = bb, key="building", geometry = "polygons")
Error in get_osm_data(location = bb, key = "building", geometry = "polygons") : 
  object 'osm_building_tags' not found
```

bb is a bbox object created with sf::st_bbox.

**Comment by elipousson** [comment]
Thanks for reporting this! `osm_building_tags` had been stored as internal system data so I think I may have overwritten in by mistake when exporting something else earlier this week. I exported `osm_building_tags` and confirmed that it works (even though the server is still kicking back errors sometimes). It should work now so please let me know if you update but continue to encounter the issue.

For your information, the no tag option for buildings often kicks back an error if you have a bounding box larger than a few blocks in any dense urban area. I think the issue is with the Overpass server capacity but I still plan on adding a check to warn users if their query covers too large an area and may fail.

The errors may also have something to do with the large number of tags in the query so I may try converting osm_building_tags into a function that only returns the most common tags by default. The full list of 84 tags include sty, houseboat, static_caravan, slurry_tank, and tree_house so not all tags are applicable in every location.
